import type { CatalogFormState, CatalogTemplateDefinition } from "./catalog.types"

const RESOURCE_PRESET_OPTIONS: CatalogTemplateDefinition["resourcePresetOptions"] = [
  { value: "small", label: "Small (100m / 256Mi)" },
  { value: "medium", label: "Medium (250m / 512Mi)" },
  { value: "large", label: "Large (500m / 1Gi)" },
]

export const CATALOG_TEMPLATES: CatalogTemplateDefinition[] = [
  {
    id: "azure_netapp_files",
    name: "Azure NetApp Files",
    description: "Enterprise file storage with high performance and availability",
    locationType: "Local",
    tools: 0,
    defaultServerUrl: "https://mcp-anf-us-east-1.netapp.com",
    defaultAuthType: "enterprise_jwt_oidc",
    runtimeCredential: {
      type: "azure_cloud",
      helperText: "Used by the MCP runtime to authenticate to the wrapped Azure NetApp Files system. Distinct from the gateway-auth credential below.",
      isRequired: true,
    },
    envVars: [
      { key: "AZURE_SUBSCRIPTION_ID", value: "", placeholder: "Enter AZURE_SUBSCRIPTION_ID", helperText: "Azure subscription ID (maps to subscriptionId API param).", isRequired: true },
      { key: "AZURE_RESOURCE_GROUP", value: "", placeholder: "Enter AZURE_RESOURCE_GROUP", helperText: "Azure resource group name (maps to resourceGroupName API param).", isRequired: true },
      { key: "ANF_ACCOUNT_NAME", value: "", placeholder: "Enter ANF_ACCOUNT_NAME", helperText: "Azure NetApp Files account name (maps to accountName API param).", isRequired: true },
    ],
    hasResourcePreset: true,
    resourcePresetOptions: RESOURCE_PRESET_OPTIONS,
    defaultResourcePreset: "small",
  },
  {
    id: "fsxn",
    name: "Amazon FSxN",
    description: "Fully managed NetApp ONTAP file storage on AWS",
    locationType: "Local",
    tools: 0,
    defaultServerUrl: "https://mcp-fsxn-us-east-1.netapp.com",
    defaultAuthType: "enterprise_jwt_oidc",
    // FSx for NetApp ONTAP speaks the ONTAP REST API, so this template reuses
    // the NetApp ONTAP MCP image (see resolveCatalogId -> ontap_mcp_official).
    // It needs a NetApp ONTAP credential (fsxadmin/vsadmin) and the FSxN
    // management endpoint — same shape as the NetApp ONTAP template.
    runtimeCredential: {
      type: "ontap",
      helperText: "NetApp ONTAP credential (fsxadmin/vsadmin username + password) the MCP runtime uses to authenticate to the FSx for NetApp ONTAP management endpoint. Distinct from the gateway-auth credential below.",
      isRequired: true,
    },
    envVars: [
      { key: "ONTAP_CLUSTER_URL", value: "", placeholder: "Enter ONTAP_CLUSTER_URL", helperText: "FSx for NetApp ONTAP management endpoint URL (e.g. https://management.fs-0123456789abcdef.fsx.us-east-1.amazonaws.com).", isRequired: true },
      { key: "ONTAP_VERIFY_TLS", value: "true", helperText: "Verify TLS certificate (true/false)." },
      { key: "ONTAP_DEFAULT_SVM", value: "", placeholder: "Enter ONTAP_DEFAULT_SVM", helperText: "Optional default storage virtual machine (SVM) name to scope tool calls." },
    ],
    hasResourcePreset: true,
    resourcePresetOptions: RESOURCE_PRESET_OPTIONS,
    defaultResourcePreset: "small",
  },
  {
    id: "google_cloud_netapp_volumes",
    name: "Google Cloud NetApp Volumes",
    description: "Unified object storage with global edge caching and multi-region replication",
    locationType: "Local",
    tools: 0,
    defaultServerUrl: "https://mcp-gcnv-us-east-1.netapp.com",
    defaultAuthType: "enterprise_jwt_oidc",
    runtimeCredential: {
      type: "gcp",
      helperText: "Used by the MCP runtime to authenticate to the wrapped gcp system. Distinct from the gateway-auth credential below.",
      isRequired: true,
    },
    envVars: [
      { key: "GOOGLE_CLOUD_PROJECT", value: "", placeholder: "Enter GOOGLE_CLOUD_PROJECT", helperText: "GCP project ID — pass as projectId on tool calls (this value is exposed to the pod for operator/agent context).", isRequired: true },
      { key: "GOOGLE_CLOUD_LOCATION", value: "", placeholder: "Enter GOOGLE_CLOUD_LOCATION", helperText: "Default GCP region or zone (e.g. us-central1) — pass as location on tool calls where applicable.", isRequired: true },
      { key: "GCNV_API_ENDPOINT", value: "", placeholder: "Enter GCNV_API_ENDPOINT", helperText: "Optional custom NetApp Volumes API endpoint (rare; see upstream GCNV_API_ENDPOINT)." },
    ],
    hasResourcePreset: true,
    resourcePresetOptions: RESOURCE_PRESET_OPTIONS,
    defaultResourcePreset: "small",
  },
  {
    id: "google_cloud_netapp_volumes_logs",
    name: "Google Cloud NetApp Volumes Logs",
    description: "Read-only GCNV logs, errors, and events from Google Cloud Logging",
    locationType: "Local",
    tools: 4,
    defaultServerUrl: "https://mcp-gcnv-logs-us-east-1.netapp.com",
    defaultAuthType: "enterprise_jwt_oidc",
    runtimeCredential: {
      type: "gcp",
      helperText: "Used by the MCP runtime to authenticate to Google Cloud Logging. Needs roles/logging.viewer. Distinct from the gateway-auth credential below.",
      isRequired: true,
    },
    envVars: [
      { key: "GOOGLE_CLOUD_PROJECT", value: "", placeholder: "Enter GOOGLE_CLOUD_PROJECT", helperText: "GCP project ID whose GCNV logs will be read — pass as projectId on tool calls.", isRequired: true },
      { key: "GOOGLE_CLOUD_LOCATION", value: "", placeholder: "Enter GOOGLE_CLOUD_LOCATION", helperText: "Optional default GCP region or zone (e.g. us-central1) for scoping tool calls." },
    ],
    hasResourcePreset: true,
    resourcePresetOptions: RESOURCE_PRESET_OPTIONS,
    defaultResourcePreset: "small",
  },
  {
    id: "azure_netapp_files_logs",
    name: "Azure NetApp Files Logs",
    description: "Read-only ANF logs, errors, and events from the Azure Monitor Activity Log",
    locationType: "Local",
    tools: 4,
    defaultServerUrl: "https://mcp-anf-logs-us-east-1.netapp.com",
    defaultAuthType: "enterprise_jwt_oidc",
    runtimeCredential: {
      type: "azure_cloud",
      helperText: "Used by the MCP runtime to authenticate to the Azure Monitor Activity Log. Needs Reader (or Monitoring Reader) on the subscription. Distinct from the gateway-auth credential below.",
      isRequired: true,
    },
    envVars: [
      { key: "AZURE_SUBSCRIPTION_ID", value: "", placeholder: "Enter AZURE_SUBSCRIPTION_ID", helperText: "Azure subscription id whose ANF Activity Log will be read — default subscriptionId on tool calls.", isRequired: true },
      { key: "AZURE_DEFAULT_REGION", value: "", placeholder: "Enter AZURE_DEFAULT_REGION", helperText: "Optional default Azure region (e.g. eastus) for operator/agent context." },
      { key: "AZURE_RESOURCE_GROUP", value: "", placeholder: "Enter AZURE_RESOURCE_GROUP", helperText: "Optional default resource group to scope tool calls." },
    ],
    hasResourcePreset: true,
    resourcePresetOptions: RESOURCE_PRESET_OPTIONS,
    defaultResourcePreset: "small",
  },
  {
    id: "netapp_ontap",
    name: "NetApp ONTAP",
    description: "Unified storage operating system for on-premises and hybrid cloud",
    locationType: "Local",
    tools: 0,
    defaultServerUrl: "https://mcp-ontap-us-east-1.netapp.com",
    defaultAuthType: "enterprise_jwt_oidc",
    runtimeCredential: {
      type: "ontap",
      helperText: "Used by the MCP runtime to authenticate to the wrapped ontap system. Distinct from the gateway-auth credential below.",
      isRequired: true,
    },
    envVars: [
      { key: "ONTAP_CLUSTER_URL", value: "", placeholder: "Enter ONTAP_CLUSTER_URL", helperText: "ONTAP cluster management URL (e.g. https://cluster.example.com)", isRequired: true },
      { key: "ONTAP_VERIFY_TLS", value: "true", helperText: "Verify TLS certificate (true/false)" },
      { key: "ONTAP_DEFAULT_SVM", value: "", placeholder: "Enter ONTAP_DEFAULT_SVM", helperText: "Optional default SVM name to scope tool calls" },
    ],
    hasResourcePreset: true,
    resourcePresetOptions: RESOURCE_PRESET_OPTIONS,
    defaultResourcePreset: "small",
  },
  {
    id: "analytics_datasets",
    name: "Analytics Datasets",
    description: "Query and analyze structured datasets with built-in analytics engine",
    locationType: "Local",
    tools: 0,
    defaultServerUrl: "https://mcp-analytics.netapp.com",
    defaultAuthType: "no_auth",
    envVars: [
      { key: "ANALYTICS_ENGINE_URL", value: "http://analytics-engine:5000", helperText: "Analytics engine base URL" },
      { key: "MAX_ROWS", value: "500", helperText: "Maximum rows returned per query" },
    ],
    hasResourcePreset: true,
    resourcePresetOptions: RESOURCE_PRESET_OPTIONS,
    defaultResourcePreset: "small",
  },
  {
    id: "duckdb_iceberg",
    name: "DuckDB Iceberg",
    description: "High-performance analytical queries on Apache Iceberg tables",
    locationType: "Local",
    tools: 0,
    defaultServerUrl: "https://mcp-duckdb-iceberg.netapp.com",
    defaultAuthType: "no_auth",
    envVars: [
      { key: "WAREHOUSE_NAME", value: "nemo", helperText: "Lakekeeper warehouse name" },
      { key: "LAKEKEEPER_CATALOG_URL", value: "http://lakekeeper:8181/catalog", helperText: "Lakekeeper catalog REST URL" },
      { key: "KEYCLOAK_TOKEN_URL", value: "http://keycloak.agentstudio-identity.svc.cluster.local:8080/realms/nemo/protocol/openid-connect/token", helperText: "Keycloak OIDC token endpoint URL" },
      { key: "MAX_ROWS", value: "500", helperText: "Maximum rows returned per query" },
    ],
    hasResourcePreset: true,
    resourcePresetOptions: RESOURCE_PRESET_OPTIONS,
    defaultResourcePreset: "medium",
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    description: "Read-only access to PostgreSQL databases — schema inspection and SQL query execution",
    locationType: "Local",
    tools: 0,
    defaultServerUrl: "",
    defaultAuthType: "no_auth",
    envVars: [
      { key: "POSTGRES_CONNECTION_STRING", value: "", placeholder: "postgresql://user:pass@host:5432/db", helperText: "PostgreSQL connection URI (credentials are stored as a secret)", isRequired: true },
    ],
    hasResourcePreset: true,
    resourcePresetOptions: RESOURCE_PRESET_OPTIONS,
    defaultResourcePreset: "small",
  },
  {
    id: "github",
    name: "GitHub",
    description: "Access GitHub repositories, issues, pull requests, and workflows via the GitHub API",
    locationType: "Local",
    tools: 0,
    defaultServerUrl: "",
    defaultAuthType: "no_auth",
    envVars: [
      { key: "GITHUB_PERSONAL_ACCESS_TOKEN", value: "", placeholder: "ghp_...", helperText: "GitHub Personal Access Token with repo scope", isRequired: true },
    ],
    hasResourcePreset: true,
    resourcePresetOptions: RESOURCE_PRESET_OPTIONS,
    defaultResourcePreset: "small",
  },
  {
    id: "web_search",
    name: "Tavily Web Search",
    description: "Internet search via Tavily — current web results with configurable depth, result count, and domain filtering",
    locationType: "Local",
    tools: 1,
    defaultServerUrl: "",
    defaultAuthType: "no_auth",
    envVars: [
      { key: "TAVILY_API_KEY", value: "", placeholder: "tvly-...", helperText: "Tavily API key — obtain from app.tavily.com", isRequired: true },
      { key: "TAVILY_MAX_RESULTS", value: "5", helperText: "Maximum search results returned per query (1–10)" },
      { key: "TAVILY_MAX_RETRIES", value: "1", helperText: "Maximum retries on transient provider failures (0–3)" },
      { key: "TAVILY_TIMEOUT_MS", value: "10000", helperText: "Per-request timeout in milliseconds (1000–30000)" },
      { key: "TAVILY_ALLOWED_DOMAINS", value: "", helperText: "Comma-separated domain allowlist — leave empty for no restriction" },
    ],
    hasResourcePreset: true,
    resourcePresetOptions: RESOURCE_PRESET_OPTIONS,
    defaultResourcePreset: "small",
  },
]

export const ADD_TOOL_DEFAULT_CATALOG_STATE: CatalogFormState = {
  selectedTemplateId: null,
  catalogName: "",
  catalogDescription: "",
  envVarValues: {},
  runtimeCredentialId: "",
  resourcePreset: "small",
  addCustomHeaders: false,
  customHeaders: [{ key: "", value: "" }],
  applyRateLimiting: false,
  callsPerMinute: "60",
  retryCount: "3",
  timeoutMs: "30000",
  isRetryTimeoutExpanded: false,
  mcpConfigDialogOpen: false,
  mcpConfigSaved: false,
  catalogMcpConnectionStatus: "not_configured",
  catalogMcpValidationMessage: null,
}
