{{- if and .Values.certs.enabled .Values.certs.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certs.secretName }}
  labels:
    app.kubernetes.io/name: netapp-ca-certs
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{ .Values.certs.certFileName }}: {{ .Files.Get (printf "files/%s" .Values.certs.certFileName) | b64enc }}
{{- end }}
