package swagger

import (
	"embed"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"

	"github.com/go-chi/chi/v5"
	"gopkg.in/yaml.v3"
)

// This file is generated by scripts/consolidate-openapi.py during build
// It is copied to the swagger directory during Docker build
//
//go:embed openapi-consolidated.yaml
var consolidatedSpec embed.FS

// getEnvOrDefault returns the value of an environment variable or a default value
func getEnvOrDefault(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

// SetupSwaggerUI sets up Swagger UI routes in the chi router
func SetupSwaggerUI(r chi.Router, basePath string) error {
	// Try to load consolidated spec from embedded file or filesystem
	var specData []byte
	var err error

	// First try embedded file
	specData, err = consolidatedSpec.ReadFile("openapi-consolidated.yaml")
	if err != nil {
		// Fallback to filesystem (for development)
		specData, err = os.ReadFile("openapi-consolidated.yaml")
		if err != nil {
			// Try relative to current working directory
			specData, err = os.ReadFile("./openapi-consolidated.yaml")
			if err != nil {
				return fmt.Errorf("failed to load OpenAPI spec (tried embedded and filesystem): %w", err)
			}
		}
	}

	// Parse YAML
	var spec map[string]interface{}
	if err := yaml.Unmarshal(specData, &spec); err != nil {
		return fmt.Errorf("failed to parse YAML: %w", err)
	}

	// Convert to JSON for Swagger UI
	specJSON, err := json.Marshal(spec)
	if err != nil {
		return fmt.Errorf("failed to marshal OpenAPI spec: %w", err)
	}

	// Get OAuth2 client ID from environment (default to swagger-ui client)
	// This should be a public client in Keycloak configured for the Swagger UI
	oauthClientID := getEnvOrDefault("SWAGGER_OAUTH_CLIENT_ID", "agentstudio-swagger")

	// Serve the OpenAPI spec as JSON
	r.Get(basePath+"/openapi.json", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write(specJSON)
	})

	// Serve OAuth2 redirect page for Swagger UI
	r.Get(basePath+"/oauth2-redirect.html", func(w http.ResponseWriter, r *http.Request) {
		// This is the standard Swagger UI OAuth2 redirect page
		html := `<!doctype html>
<html lang="en-US">
<head>
    <title>Swagger UI: OAuth2 Redirect</title>
</head>
<body>
<script>
    'use strict';
    function run () {
        var oauth2 = window.opener.swaggerUIRedirectOauth2;
        var sentState = oauth2.state;
        var redirectUrl = oauth2.redirectUrl;
        var isValid, qp, arr;

        if (/code|token|error/.test(window.location.hash)) {
            qp = window.location.hash.substring(1).replace('?', '&');
        } else {
            qp = location.search.substring(1);
        }

        arr = qp.split("&");
        arr.forEach(function (v,i,_arr) { _arr[i] = '"' + v.replace('=', '":"') + '"';});
        qp = qp ? JSON.parse('{' + arr.join() + '}',
                function (key, value) {
                    return key === "" ? value : decodeURIComponent(value);
                }
        ) : {};

        isValid = qp.state === sentState;

        if ((
          oauth2.auth.schema.get("flow") === "accessCode" ||
          oauth2.auth.schema.get("flow") === "authorizationCode" ||
          oauth2.auth.schema.get("flow") === "authorization_code"
        ) && !oauth2.auth.code) {
            if (!isValid) {
                oauth2.errCb({
                    authId: oauth2.auth.name,
                    source: "auth",
                    level: "warning",
                    message: "Authorization may be unsafe, passed state was changed in server. The passed state wasn't returned from auth server."
                });
            }

            if (qp.code) {
                delete oauth2.state;
                oauth2.auth.code = qp.code;
                oauth2.callback({auth: oauth2.auth, redirectUrl: redirectUrl});
            } else {
                let oauthErrorMsg;
                if (qp.error) {
                    oauthErrorMsg = "["+qp.error+"]: " +
                        (qp.error_description ? qp.error_description+ ". " : "no accessCode received from the server. ") +
                        (qp.error_uri ? "More info: "+qp.error_uri : "");
                }

                oauth2.errCb({
                    authId: oauth2.auth.name,
                    source: "auth",
                    level: "error",
                    message: oauthErrorMsg || "[Authorization failed]: no accessCode received from the server."
                });
            }
        } else {
            oauth2.callback({auth: oauth2.auth, token: qp, isValid: isValid, redirectUrl: redirectUrl});
        }
        window.close();
    }

    if (document.readyState !== 'loading') {
        run();
    } else {
        document.addEventListener('DOMContentLoaded', function () {
            run();
        });
    }
</script>
</body>
</html>`
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Write([]byte(html))
	})

	// Create handler function for Swagger UI HTML
	swaggerUIHandler := func(w http.ResponseWriter, r *http.Request) {
		title := "AgentStudio Services API"
		if info, ok := spec["info"].(map[string]interface{}); ok {
			if t, ok := info["title"].(string); ok {
				title = t
			}
		}

		html := fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>%s</title>
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui.css" />
  <style>
    html {
      box-sizing: border-box;
      overflow: -moz-scrollbars-vertical;
      overflow-y: scroll;
    }
    *, *:before, *:after {
      box-sizing: inherit;
    }
    body {
      margin:0;
      background: #fafafa;
    }
  </style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"></script>
  <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js"></script>
  <script>
    window.onload = function() {
      const ui = SwaggerUIBundle({
        url: "%s/openapi.json",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout",
        // OAuth2 configuration for Keycloak
        oauth2RedirectUrl: window.location.origin + "%s/oauth2-redirect.html",
        initOAuth: {
          clientId: "%s",
          scopes: "openid profile email",
          usePkceWithAuthorizationCodeGrant: true
        }
      });
    };
  </script>
</body>
</html>`, title, basePath, basePath, oauthClientID)

		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.Write([]byte(html))
	}

	// Serve Swagger UI - handle both /api-docs and /api-docs/
	r.Get(basePath, swaggerUIHandler)
	r.Get(basePath+"/", swaggerUIHandler)

	log.Printf("Swagger UI available at %s and %s/", basePath, basePath)
	log.Printf("OAuth2 client ID for Swagger UI: %s", oauthClientID)
	return nil
}
