import { body } from 'express-validator';

export const createModelValidator = [
  body('name').isString().notEmpty().withMessage('name is required'),
  body('displayName').optional().isString(),
  body('provider').optional().isString().isIn(['openai', 'openai_compatible', 'aws_bedrock', 'azure', 'google', 'gemini', 'anthropic', 'ollama', 'cohere', 'perplexity', 'huggingface', 'fireworks']),
  body('providerModelId').optional().isString(),
  body('providerDeploymentName').optional().isString(),
  body('gatewayModelId').optional().isString(),
  body('gatewayBindingName').optional().isString(),
  body('credentialId').optional().isUUID(),
  body('modelType').optional().isString().isIn(['llm', 'embedding']),
  body('modelClass').optional().isString(),
  body('model_info').optional().isObject(),
  body('model_info.architecture').optional().isString(),
  body('model_info.base_model').optional().isString(),
  body('model_info.variant').optional().isString(),
  body('model_info.parameters').optional().isString(),
  body('model_info.quantization').optional().isString(),
  body('model_info.size').optional().isNumeric(),
  // Embedding-model catalog fields — populated by enrichModelInfoFromCatalog
  // at registration time (see providers/embeddingDimensions.ts).
  body('model_info.dimensions').optional().isInt({ min: 1 }),
  body('model_info.recommendedChunkSize').optional().isInt({ min: 1 }),
  body('model_info.category').optional().isString().isIn(['balanced', 'quality', 'fast', 'multilingual']),
  body('model_info.description').optional().isString(),
  body('endpoint').optional().isString(),
  body('auth').optional().isObject(),
  body('auth.access_token').optional().isString(),
  body('auth.secret_key').optional().isString(),
  body('limits').optional().isObject(),
  body('limits.tpm').optional().isNumeric(),
  body('limits.timeout').optional().isNumeric(),
  body('limits.stream_timeout').optional().isNumeric(),
  body('limits.max_retries').optional().isNumeric(),
  body('rateCardOverride').optional().isObject(),
  body('rpm').optional({ nullable: true }).isInt({ min: 0 }).withMessage('rpm must be a non-negative integer'),
  body('tpm').optional({ nullable: true }).isInt({ min: 0 }).withMessage('tpm must be a non-negative integer'),
  body('spendingLimit').optional({ nullable: true }).isFloat({ min: 0 }).withMessage('spendingLimit must be a non-negative number'),
  body('spendingLimitPeriod').optional({ nullable: true }).isIn(['day', 'week', 'month']).withMessage('spendingLimitPeriod must be "day", "week", or "month"'),
  body('inputCostPer1M').optional({ nullable: true }).isFloat({ min: 0 }).withMessage('inputCostPer1M must be a non-negative number'),
  body('outputCostPer1M').optional({ nullable: true }).isFloat({ min: 0 }).withMessage('outputCostPer1M must be a non-negative number'),
  body('markupPercent').optional({ nullable: true }).isFloat({ min: 0 }).withMessage('markupPercent must be a non-negative number'),
  body('concurrentRequests').optional({ nullable: true }).isInt({ min: 1 }).withMessage('concurrentRequests must be a positive integer'),
  body('bufferSize').optional({ nullable: true }).isInt({ min: 1 }).withMessage('bufferSize must be a positive integer'),
];

export const updateModelValidator = [
  body('name').optional().isString(),
  body('displayName').optional().isString(),
  body('provider').optional().isString().isIn(['openai', 'openai_compatible', 'aws_bedrock', 'azure', 'google', 'gemini', 'anthropic', 'ollama', 'cohere', 'perplexity', 'huggingface', 'fireworks']),
  body('providerModelId').optional().isString(),
  body('providerDeploymentName').optional().isString(),
  body('gatewayModelId').optional().isString(),
  body('gatewayBindingName').optional().isString(),
  body('credentialId').optional().isUUID(),
  body('modelType').optional().isString().isIn(['llm', 'embedding']),
  body('modelClass').optional().isString(),
  body('model_info').optional().isObject(),
  body('model_info.architecture').optional().isString(),
  body('model_info.base_model').optional().isString(),
  body('model_info.variant').optional().isString(),
  body('model_info.parameters').optional().isString(),
  body('model_info.quantization').optional().isString(),
  body('model_info.size').optional().isNumeric(),
  // Embedding-model catalog fields (see providers/embeddingDimensions.ts).
  body('model_info.dimensions').optional().isInt({ min: 1 }),
  body('model_info.recommendedChunkSize').optional().isInt({ min: 1 }),
  body('model_info.category').optional().isString().isIn(['balanced', 'quality', 'fast', 'multilingual']),
  body('model_info.description').optional().isString(),
  body('endpoint').optional().isString(),
  body('auth').optional().isObject(),
  body('auth.access_token').optional().isString(),
  body('auth.secret_key').optional().isString(),
  body('limits').optional().isObject(),
  body('limits.tpm').optional().isNumeric(),
  body('limits.timeout').optional().isNumeric(),
  body('limits.stream_timeout').optional().isNumeric(),
  body('limits.max_retries').optional().isNumeric(),
  body('rateCardOverride').optional().isObject(),
  body('rpm').optional({ nullable: true }).isInt({ min: 0 }).withMessage('rpm must be a non-negative integer'),
  body('tpm').optional({ nullable: true }).isInt({ min: 0 }).withMessage('tpm must be a non-negative integer'),
  body('spendingLimit').optional({ nullable: true }).isFloat({ min: 0 }).withMessage('spendingLimit must be a non-negative number'),
  body('spendingLimitPeriod').optional({ nullable: true }).isIn(['day', 'week', 'month']).withMessage('spendingLimitPeriod must be "day", "week", or "month"'),
  body('inputCostPer1M').optional({ nullable: true }).isFloat({ min: 0 }).withMessage('inputCostPer1M must be a non-negative number'),
  body('outputCostPer1M').optional({ nullable: true }).isFloat({ min: 0 }).withMessage('outputCostPer1M must be a non-negative number'),
  body('markupPercent').optional({ nullable: true }).isFloat({ min: 0 }).withMessage('markupPercent must be a non-negative number'),
];
