{{- if and .Values.enabled (default false .Values.metrics.serviceMonitor.enabled) (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: config-service
  labels:
    {{- include "config-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "config-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ default "http" .Values.metrics.port }}
      path: {{ default "/metrics" .Values.metrics.path }}
      interval: {{ default "30s" .Values.metrics.serviceMonitor.interval }}
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: exported_service_name
{{- end }}
