{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "connector-worker.serviceAccountName" . }}
  labels:
    {{- include "connector-worker.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.azureClientId }}
  annotations:
    azure.workload.identity/client-id: {{ . | quote }}
  {{- end }}
{{- end }}
