{{- if .Values.enabled }}
{{- if not .Values.internalToken.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-proxy.fullname" . }}-internal
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "prometheus-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  internalToken: {{ .Values.internalToken.value | quote }}
{{- end }}
{{- end }}
