export const TEMPLATE_SELECTION_STRINGS = {
  DIALOG_TITLE: "Select a template",
  DIALOG_DESCRIPTION: "Select a template to create the agent.",
  /** `{count}` is replaced with the total number of templates available. */
  SECTION_TITLE_TEMPLATES: "Templates ({count})",
  COLUMN_NAME: "Name",
  COLUMN_DESCRIPTION: "Description",
  COLUMN_CAPABILITIES: "Capabilities",
  COLUMN_EXAMPLES: "Examples",
  COLUMN_INSTRUCTIONS: "Instructions",
  EXAMPLES_VIEW_LABEL: "View",
  INSTRUCTIONS_VIEW_LABEL: "View",
  SEARCH_ARIA_LABEL: "Search templates",
  SEARCH_PLACEHOLDER: "Search by name or description",
  CLOSE_SEARCH_ARIA_LABEL: "Close search",
  NO_MATCH_MESSAGE: "No templates match your search.",
  EMPTY_CATALOG_MESSAGE: "No templates available.",
  SORT_ARIA_LABEL: "Sort column",
  RADIO_ARIA_LABEL: "Select template {name}",
  PAGINATION_RANGE: "{start} - {end} of {total}",
  PAGE_FIRST_ARIA_LABEL: "First page",
  PAGE_PREV_ARIA_LABEL: "Previous page",
  PAGE_NEXT_ARIA_LABEL: "Next page",
  PAGE_LAST_ARIA_LABEL: "Last page",
  SELECT_ACTION_LABEL: "Select",
  CLOSE_ACTION_LABEL: "Close",
} as const;
