#!/bin/bash
# Setup DNS Server (dnsmasq) for Local Development
# This script installs and configures dnsmasq for automatic DNS resolution

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration - can be overridden via environment variables
BASE_DOMAIN="${BASE_DOMAIN:-agentstudio.local}"
DNSMASQ_CONF="${DNSMASQ_CONF:-/etc/dnsmasq.conf}"
DNSMASQ_HOSTS_DIR="${DNSMASQ_HOSTS_DIR:-/etc/dnsmasq/hosts.d}"
RESOLVER_DIR="/etc/resolver"

echo -e "${GREEN}Setting up DNS server (dnsmasq) for local development...${NC}"
echo "Base domain: $BASE_DOMAIN"
echo ""

# Detect OS
if [[ "$OSTYPE" == "darwin"* ]]; then
    OS="macos"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    OS="linux"
else
    echo -e "${RED}Error: Unsupported OS: $OSTYPE${NC}"
    exit 1
fi

echo -e "${YELLOW}Detected OS: $OS${NC}"
echo ""

# Step 1: Install dnsmasq
echo -e "${YELLOW}Step 1: Installing dnsmasq...${NC}"

if command -v dnsmasq &> /dev/null; then
    echo -e "${GREEN}✅ dnsmasq is already installed${NC}"
    dnsmasq --version | head -n1
else
    if [ "$OS" = "macos" ]; then
        if command -v brew &> /dev/null; then
            echo "Installing dnsmasq via Homebrew..."
            brew install dnsmasq
            echo -e "${GREEN}✅ dnsmasq installed${NC}"
        else
            echo -e "${RED}Error: Homebrew is required for macOS. Please install Homebrew first.${NC}"
            exit 1
        fi
    else
        # Linux
        if command -v apt-get &> /dev/null; then
            echo "Installing dnsmasq via apt-get..."
            sudo apt-get update
            sudo apt-get install -y dnsmasq
            echo -e "${GREEN}✅ dnsmasq installed${NC}"
        elif command -v yum &> /dev/null; then
            echo "Installing dnsmasq via yum..."
            sudo yum install -y dnsmasq
            echo -e "${GREEN}✅ dnsmasq installed${NC}"
        else
            echo -e "${RED}Error: Could not determine package manager. Please install dnsmasq manually.${NC}"
            exit 1
        fi
    fi
fi

echo ""

# Step 2: Create dnsmasq configuration directory
echo -e "${YELLOW}Step 2: Creating dnsmasq configuration directory...${NC}"

if [ ! -d "$DNSMASQ_HOSTS_DIR" ]; then
    sudo mkdir -p "$DNSMASQ_HOSTS_DIR"
    sudo chmod 755 "$DNSMASQ_HOSTS_DIR"
    echo -e "${GREEN}✅ Created directory: $DNSMASQ_HOSTS_DIR${NC}"
else
    echo -e "${GREEN}✅ Directory already exists: $DNSMASQ_HOSTS_DIR${NC}"
fi

echo ""

# Step 3: Configure dnsmasq
echo -e "${YELLOW}Step 3: Configuring dnsmasq...${NC}"

# Backup existing config if it exists
if [ -f "$DNSMASQ_CONF" ]; then
    BACKUP_FILE="${DNSMASQ_CONF}.backup.$(date +%Y%m%d_%H%M%S)"
    echo "Backing up existing config to: $BACKUP_FILE"
    sudo cp "$DNSMASQ_CONF" "$BACKUP_FILE"
fi

# Create/update dnsmasq configuration
TEMP_CONF=$(mktemp)
cat > "$TEMP_CONF" <<EOF
# dnsmasq configuration for AgentStudio local development
# Generated by setup-dns-server.sh

# Listen on localhost only
listen-address=127.0.0.1

# Don't read /etc/hosts (we'll use hosts.d directory instead)
no-hosts

# Read host entries from hosts.d directory
addn-hosts=$DNSMASQ_HOSTS_DIR

# Base domain resolution.
# dnsmasq's address= is recursive: this single line resolves $BASE_DOMAIN itself
# and EVERY subdomain at any depth (auth., s3., catalog., workflows., phoenix.,
# ws-<id>., etc.) to 127.0.0.1. No additional wildcard lines are needed —
# in particular, the legacy "address=/ws.$BASE_DOMAIN/" line was redundant
# under this entry and has been removed now that workspaces use the
# single-label form ws-<id>.$BASE_DOMAIN instead of <id>.ws.$BASE_DOMAIN.
address=/$BASE_DOMAIN/127.0.0.1

# Log queries for debugging (comment out for production)
# log-queries
# log-facility=/var/log/dnsmasq.log

# Cache size
cache-size=1000

# Don't forward private IP ranges
bogus-priv

# Enable DNSSEC validation
dnssec

# Don't poll /etc/resolv.conf
no-resolv

# Use Google DNS as upstream (can be customized)
server=8.8.8.8
server=8.8.4.4
EOF

# Check if our config section already exists
if grep -q "# dnsmasq configuration for AgentStudio" "$DNSMASQ_CONF" 2>/dev/null; then
    echo -e "${YELLOW}⚠️  AgentStudio configuration section already exists in $DNSMASQ_CONF${NC}"
    echo "Skipping config update. If you need to update, edit $DNSMASQ_CONF manually."
else
    # Append to existing config or create new
    if [ -f "$DNSMASQ_CONF" ]; then
        echo "" | sudo tee -a "$DNSMASQ_CONF" > /dev/null
        cat "$TEMP_CONF" | sudo tee -a "$DNSMASQ_CONF" > /dev/null
    else
        cat "$TEMP_CONF" | sudo tee "$DNSMASQ_CONF" > /dev/null
    fi
    echo -e "${GREEN}✅ dnsmasq configuration updated${NC}"
fi

rm -f "$TEMP_CONF"

echo ""

# Step 4: Configure macOS resolver (macOS only)
if [ "$OS" = "macos" ]; then
    echo -e "${YELLOW}Step 4: Configuring macOS resolver for $BASE_DOMAIN...${NC}"
    
    if [ ! -d "$RESOLVER_DIR" ]; then
        sudo mkdir -p "$RESOLVER_DIR"
        echo -e "${GREEN}✅ Created resolver directory: $RESOLVER_DIR${NC}"
    fi
    
    RESOLVER_FILE="${RESOLVER_DIR}/${BASE_DOMAIN}"
    if [ -f "$RESOLVER_FILE" ]; then
        echo -e "${GREEN}✅ Resolver config already exists: $RESOLVER_FILE${NC}"
    else
        echo "nameserver 127.0.0.1" | sudo tee "$RESOLVER_FILE" > /dev/null
        echo -e "${GREEN}✅ Created resolver config: $RESOLVER_FILE${NC}"
    fi
    echo ""
fi

# Step 5: Start dnsmasq service
echo -e "${YELLOW}Step 5: Starting dnsmasq service...${NC}"

if [ "$OS" = "macos" ]; then
    if command -v brew &> /dev/null; then
        # Check if dnsmasq is already running
        if brew services list | grep -q "dnsmasq.*started"; then
            echo -e "${GREEN}✅ dnsmasq is already running${NC}"
            # Restart to pick up new config
            sudo brew services restart dnsmasq || {
                echo -e "${YELLOW}⚠️  Could not restart dnsmasq via brew services${NC}"
                echo "Trying to start manually..."
                sudo dnsmasq --no-daemon --test 2>/dev/null && {
                    sudo killall dnsmasq 2>/dev/null || true
                    sudo dnsmasq
                } || echo -e "${YELLOW}⚠️  Could not start dnsmasq. Please start manually.${NC}"
            }
        else
            sudo brew services start dnsmasq || {
                echo -e "${RED}❌ Failed to start dnsmasq via brew services${NC}"
                echo "You may need to start it manually: sudo brew services start dnsmasq"
                exit 1
            }
            echo -e "${GREEN}✅ dnsmasq started${NC}"
        fi
    else
        echo -e "${YELLOW}⚠️  Homebrew not found. Please start dnsmasq manually.${NC}"
    fi
else
    # Linux
    if command -v systemctl &> /dev/null; then
        sudo systemctl enable dnsmasq
        sudo systemctl restart dnsmasq || {
            echo -e "${RED}❌ Failed to start dnsmasq${NC}"
            sudo systemctl status dnsmasq
            exit 1
        }
        echo -e "${GREEN}✅ dnsmasq started and enabled${NC}"
    else
        echo -e "${YELLOW}⚠️  systemctl not found. Please start dnsmasq manually.${NC}"
    fi
fi

echo ""

# Step 6: Flush DNS cache
echo -e "${YELLOW}Step 6: Flushing DNS cache...${NC}"

if [ "$OS" = "macos" ]; then
    sudo dscacheutil -flushcache
    sudo killall -HUP mDNSResponder
    echo -e "${GREEN}✅ DNS cache flushed${NC}"
else
    # Linux - depends on distribution
    if command -v systemd-resolve &> /dev/null; then
        sudo systemd-resolve --flush-caches
        echo -e "${GREEN}✅ DNS cache flushed${NC}"
    elif command -v resolvectl &> /dev/null; then
        sudo resolvectl flush-caches
        echo -e "${GREEN}✅ DNS cache flushed${NC}"
    else
        echo -e "${YELLOW}⚠️  Could not flush DNS cache (no known method)${NC}"
    fi
fi

echo ""

# Step 7: Test DNS resolution
echo -e "${YELLOW}Step 7: Testing DNS resolution...${NC}"

if dig @127.0.0.1 "$BASE_DOMAIN" +short | grep -q "127.0.0.1"; then
    echo -e "${GREEN}✅ DNS resolution working: $BASE_DOMAIN -> 127.0.0.1${NC}"
else
    echo -e "${YELLOW}⚠️  DNS resolution test failed. dnsmasq may need a moment to start.${NC}"
    echo "You can test manually with: dig @127.0.0.1 $BASE_DOMAIN"
fi

echo ""

# Summary
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✅ DNS server setup complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo "Configuration:"
echo "  - dnsmasq config: $DNSMASQ_CONF"
echo "  - hosts directory: $DNSMASQ_HOSTS_DIR"
echo "  - base domain: $BASE_DOMAIN"
if [ "$OS" = "macos" ]; then
    echo "  - resolver config: $RESOLVER_DIR/$BASE_DOMAIN"
fi
echo ""
echo "Next steps:"
echo "  1. Use scripts/dns-helper.sh to register DNS records"
echo "  2. Deploy Ray/AgentStudio services - DNS will be registered automatically"
echo ""
echo "Test DNS resolution:"
echo "  dig @127.0.0.1 $BASE_DOMAIN"
echo "  dig @127.0.0.1 app.$BASE_DOMAIN"
echo "  dig @127.0.0.1 ws-test.$BASE_DOMAIN"
echo ""

