{{- if and .Values.enabled (default false .Values.metrics.serviceMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: temporal
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "temporal.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.metrics.path | default "/metrics" }}
      interval: {{ .Values.metrics.serviceMonitor.interval | default "30s" }}
{{- end }}
