{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "analytics-mcp-server.fullname" . }}
  labels:
    {{- include "analytics-mcp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      appProtocol: http
      name: http-api
  selector:
    {{- include "analytics-mcp-server.selectorLabels" . | nindent 4 }}
{{- end }}
