"""§G5 — OpenAPI drift check.

This test regenerates the live OpenAPI document from the FastAPI app
at test time and diffs it against the committed fixture at
``tests/fixtures/openapi.expected.json``. Any unintentional drift
fails CI; intentional drift is acknowledged by re-running
``make regen-openapi`` and committing the updated fixture in the
same change.

Why it matters
--------------
Two consumers of MAF rely on the OpenAPI shape staying byte-stable:

1. **Front-end / CLI / SDK code generation** — agent-studio's front
   end derives typed clients from this spec. A silent drift breaks
   downstream type checks (§5.4.8 verification item #1).
2. **Migration plan ratchet** — §C1 (``/teams/`` → ``/agent-teams/``),
   §C2 (``PATCH .../sessions/{sid}``), and §A1-A7 (camelCase wire) are
   all observable in the spec. The drift check guarantees a code path
   does not silently re-introduce a snake_case alias or revive a
   ``/teams/`` URL.

Determinism (§H1)
-----------------
The :func:`scripts.generate_openapi.build_spec` helper produces a
deterministic document. The fixture is generated by the same helper,
so the diff is exact on every supported Python / FastAPI / Pydantic
combination pinned in ``pyproject.toml``.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

# The generator is a standalone CLI script, so it sits in ``scripts/`` --
# not in the importable package tree. Bring it in via a path append so
# the test imports ``build_spec`` directly without subprocess overhead.
_REPO_ROOT = Path(__file__).resolve().parents[2]
_SCRIPTS_DIR = _REPO_ROOT / "scripts"

import sys  # noqa: E402

if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

from generate_openapi import FIXTURE_PATH, build_spec  # noqa: E402


def _format_diff(live: dict, expected: dict) -> str:
    """Build a focussed diff message highlighting differing top-level keys."""
    live_paths = set(live.get("paths", {}).keys())
    expected_paths = set(expected.get("paths", {}).keys())
    only_live = sorted(live_paths - expected_paths)
    only_expected = sorted(expected_paths - live_paths)

    live_schemas = set(live.get("components", {}).get("schemas", {}).keys())
    expected_schemas = set(expected.get("components", {}).get("schemas", {}).keys())
    only_live_s = sorted(live_schemas - expected_schemas)
    only_expected_s = sorted(expected_schemas - live_schemas)

    parts = []
    if only_live:
        parts.append(f"  + paths added (in live, missing from fixture): {only_live}")
    if only_expected:
        parts.append(f"  - paths removed (in fixture, missing from live): {only_expected}")
    if only_live_s:
        parts.append(f"  + schemas added: {only_live_s}")
    if only_expected_s:
        parts.append(f"  - schemas removed: {only_expected_s}")
    if not parts:
        parts.append("  (top-level paths and schemas agree; the diff is in field shapes)")
    return "\n".join(parts)


@pytest.mark.integration
class TestOpenApiDrift:
    """The committed OpenAPI fixture must equal the live spec exactly."""

    def test_fixture_exists(self) -> None:
        """Bootstrap guard: the fixture must be committed.

        If this fails, run ``make regen-openapi`` once and commit
        ``tests/fixtures/openapi.expected.json``.
        """
        assert FIXTURE_PATH.exists(), (
            f"OpenAPI baseline fixture is missing at {FIXTURE_PATH}. "
            f"Run `make regen-openapi` to generate it, then commit "
            f"the file. This is required so CI can detect drift."
        )

    def test_live_spec_matches_fixture(self) -> None:
        """§G5 acceptance — live OpenAPI must equal the committed fixture.

        On drift, the assertion message tells the developer either to
        revert the unintended change or to run ``make regen-openapi``
        and commit the new fixture.
        """
        live = build_spec()
        expected = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
        if live == expected:
            return
        diff_summary = _format_diff(live, expected)
        pytest.fail(
            "OpenAPI drift detected.\n\n"
            f"{diff_summary}\n\n"
            "If this change is INTENTIONAL, run:\n"
            "    make regen-openapi\n"
            "and commit the updated tests/fixtures/openapi.expected.json "
            "alongside the code change.\n\n"
            "If this change is UNINTENTIONAL, revert the route / schema "
            "modification that altered the live spec."
        )

    def test_spec_is_deterministic(self) -> None:
        """§H1 — back-to-back invocations of build_spec() produce identical output.

        Pins the determinism contract that the §G5 drift check relies on.
        """
        a = build_spec()
        b = build_spec()
        assert json.dumps(a, sort_keys=False) == json.dumps(b, sort_keys=False), (
            "build_spec() is not deterministic across back-to-back calls. "
            "Some route or schema has order-dependent generation. "
            "Investigate `scripts/generate_openapi.py` and the underlying "
            "FastAPI app for non-deterministic registration ordering."
        )
