{{- if .Values.enabled }}
{{- $root := . }}
{{- range .Values.models }}
{{- $args := dict "root" $root "modelKey" .key }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tei.modelFullname" $args }}
  namespace: {{ $root.Values.namespace | default $root.Release.Namespace }}
  labels:
    {{- include "tei.commonLabels" $args | nindent 4 }}
    {{- include "tei.selectorLabels" $args | nindent 4 }}
spec:
  type: {{ $root.Values.service.type }}
  ports:
    - port: {{ $root.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tei.selectorLabels" $args | nindent 4 }}
{{- end }}
{{- end }}
